import {move2048,spawn2048,has2048Moves,snakeFood,stepSnake,createMinefield,revealMinefield,chordMinefield,minefieldWon} from './classic-engine.mjs';

const $=(s,root=document)=>root.querySelector(s),body=$('#game-body'),game=document.body.dataset.classic;
const memory=new Map();let storageOK=true,sound=false,audio=null;
function read(key,fallback){try{const raw=memory.get(key)||localStorage.getItem('littora.classics.v1.'+key);return raw?JSON.parse(raw):fallback;}catch{storageOK=false;return fallback;}}
function save(key,value){const raw=JSON.stringify(value);memory.set(key,raw);try{localStorage.setItem('littora.classics.v1.'+key,raw);}catch{storageOK=false;storageNotice();}}
function storageNotice(){if(!storageOK)$('[data-storage-notice]').textContent='Storage is unavailable; progress lasts for this visit.';}
function record(key){const value=read(key,0);return Number.isFinite(value)&&value>=0?value:0;}
function note(freq=440,duration=.12){if(!sound)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});const osc=audio.createOscillator(),gain=audio.createGain(),now=audio.currentTime;osc.type=game==='snake'?'triangle':'sine';osc.frequency.value=freq;gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.04,now+.015);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(now+duration+.02);}catch{sound=false;updateSound();}}
function updateSound(){const button=$('#classic-sound');button.setAttribute('aria-pressed',String(sound));button.setAttribute('aria-label',sound?'Mute sound':'Enable sound');}
$('#classic-sound').addEventListener('click',()=>{sound=!sound;updateSound();note(523,.15);});
const arrowPad=(id)=>`<div class="direction-pad" role="group" aria-label="Direction controls" id="${id}"><button data-dir="up" aria-label="Move up">↑</button><button data-dir="left" aria-label="Move left">←</button><button data-dir="down" aria-label="Move down">↓</button><button data-dir="right" aria-label="Move right">→</button></div>`;
const stat=(label,id,value='0')=>`<div class="classic-stat"><span>${label}</span><strong id="${id}">${value}</strong></div>`;
function restartConfirmation(action){const panel=$('#restart-confirm');$('#new-game').addEventListener('click',()=>{panel.hidden=false;$('#keep-game').focus();});$('#keep-game').addEventListener('click',()=>{panel.hidden=true;$('#new-game').focus();});$('#confirm-new').addEventListener('click',()=>{panel.hidden=true;action();});}
const restartPanel=`<div class="classic-confirm" id="restart-confirm" hidden><p>Start a fresh board? Your best will stay.</p><div class="button-row"><button class="subtle-button" id="keep-game">Keep playing</button><button class="primary-button" id="confirm-new">New board</button></div></div>`;

function numberloom(){
  function fresh(){return {board:spawn2048(spawn2048(Array(16).fill(0))),score:0,moves:0,won:false};}
  const raw=read('number-board',null);
  const valid=raw&&Array.isArray(raw.board)&&raw.board.length===16&&raw.board.some(Boolean)&&raw.board.every(n=>Number.isInteger(n)&&n>=0&&n<=1073741824&&(n===0||(n>=2&&Math.log2(n)%1===0)))&&Number.isSafeInteger(raw.score)&&raw.score>=0&&Number.isSafeInteger(raw.moves)&&raw.moves>=0;
  let state=valid?{board:raw.board,score:raw.score,moves:raw.moves,won:Boolean(raw.won)}:fresh(),previous=null,best=record('number-best');
  best=Math.max(best,state.score);
  body.innerHTML=`<div class="classic-room number-room"><section class="classic-main"><div class="classic-toolbar"><div class="classic-stats">${stat('Score','number-score')}${stat('Best','number-best')}${stat('Moves','number-moves')}</div><button class="subtle-button" id="number-undo" disabled>↶ Undo</button></div><div class="number-board" id="number-board" tabindex="0" role="group" aria-label="2048 board. Use arrow keys or swipe to combine matching numbers.">${Array.from({length:16},(_,i)=>`<div class="number-cell" data-cell="${i}"><span></span></div>`).join('')}</div><div class="number-controls"><p>Arrow keys · Swipe · Direction buttons</p>${arrowPad('number-directions')}</div><p class="classic-status" role="status" id="number-message">Start small. Make something greater.</p></section><aside class="classic-sidebar"><div class="bauhaus-emblem" aria-hidden="true"><span></span><i></i><b>2048</b></div><p class="classic-kicker">A CLASSIC, IN COLOUR</p><h2>Good things<br>add up.</h2><p>Slide every tile in one direction. When two matching numbers meet, they become one. Each move makes room for a new tile.</p><div class="merge-example" aria-label="Two twos merge into four"><span>2</span><b>+</b><span>2</span><b>→</b><span>4</span></div><p>Reach <strong>2048</strong>, then keep going if you like. A full board is only the end when no matching neighbours remain.</p><p class="classic-tip">A little strategy: give your largest tile a corner, and leave it room to grow.</p><button class="subtle-button" id="new-game">New board</button>${restartPanel}</aside></div>`;
  const board=$('#number-board'),cells=[...board.children],message=$('#number-message');
  function persist(){save('number-board',state);save('number-best',best);}
  function render(merged=[]){cells.forEach((cell,i)=>{const value=state.board[i];cell.dataset.value=value;cell.dataset.size=String(value).length;cell.classList.toggle('number-merged',merged.includes(i));$('span',cell).textContent=value||'';cell.setAttribute('aria-label',`Row ${Math.floor(i/4)+1}, column ${i%4+1}: ${value||'empty'}`);});$('#number-score').textContent=state.score.toLocaleString();$('#number-best').textContent=best.toLocaleString();$('#number-moves').textContent=state.moves;$('#number-undo').disabled=!previous;board.classList.toggle('number-ended',!has2048Moves(state.board));}
  function move(direction){const result=move2048(state.board,direction);if(!result.changed)return;previous=structuredClone(state);state.board=spawn2048(result.board);state.score+=result.score;state.moves++;best=Math.max(best,state.score);const wonNow=!state.won&&state.board.some(n=>n>=2048);state.won ||= wonNow;persist();render(result.merged);message.textContent=wonNow?'2048! A beautiful milestone. Keep going and see what adds up.':!has2048Moves(state.board)?'No moves left. Undo your last move, or start a fresh board.':result.score?`A lovely combination. +${result.score} points.`:'A little space for the next possibility.';if(result.score)note(wonNow?784:330+Math.min(result.score,512),.15);}
  board.addEventListener('keydown',event=>{const direction={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right'}[event.key];if(direction){event.preventDefault();move(direction);}});
  $('#number-directions').addEventListener('click',event=>{const button=event.target.closest('[data-dir]');if(button){move(button.dataset.dir);board.focus({preventScroll:true});}});
  let pointer=null;
  board.addEventListener('pointerdown',event=>{if(event.button!==0)return;pointer={x:event.clientX,y:event.clientY,id:event.pointerId};board.setPointerCapture(event.pointerId);board.focus({preventScroll:true});});
  board.addEventListener('pointerup',event=>{if(!pointer||pointer.id!==event.pointerId)return;const dx=event.clientX-pointer.x,dy=event.clientY-pointer.y;pointer=null;if(Math.max(Math.abs(dx),Math.abs(dy))>25)move(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up');});
  board.addEventListener('pointercancel',()=>pointer=null);
  $('#number-undo').addEventListener('click',()=>{if(!previous)return;state=previous;previous=null;persist();render();message.textContent='One step back. A new possibility.';board.focus({preventScroll:true});});
  restartConfirmation(()=>{state=fresh();previous=null;persist();render();message.textContent='A fresh start. Find your first combination.';board.focus();});
  render();if(!has2048Moves(state.board))message.textContent='No moves left. Start a fresh board and try a new approach.';persist();return()=>{};
}

function picnicSnake(){
  const size=18,speeds={leisurely:185,brisk:125,speedy:85},vectors={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}};
  let snake=[],food=null,direction=vectors.right,queued=null,mode='leisurely',score=0,best=record('snake-best-'+mode),phase='ready',frame=0,last=0,accumulator=0,disposed=false;
  body.innerHTML=`<div class="classic-room snake-room"><section class="classic-main"><div class="classic-toolbar"><div class="classic-stats">${stat('Apples','snake-score')}${stat('Best','snake-best')}</div><span class="picnic-ticket">18 × 18<br>APPLE CLUB</span></div><div class="picnic-mat"><canvas id="snake-canvas" width="648" height="648" tabindex="0" aria-label="Snake game. Arrow keys or WASD to steer. Space to start or pause."></canvas></div><div class="snake-actions"><div class="button-row"><button class="primary-button" id="snake-start">Let’s picnic</button><button class="subtle-button" id="snake-pause" disabled>Pause</button></div>${arrowPad('snake-directions')}</div><p class="classic-status" role="status" id="snake-message">An apple a day. A longer snake every time.</p></section><aside class="classic-sidebar"><div class="picnic-illustration" aria-hidden="true"><span class="picnic-sun">☀</span><svg viewBox="0 0 210 120"><path d="M25 94H100Q126 94 126 65V51Q126 27 155 27" fill="none" stroke="#31563f" stroke-width="28" stroke-linecap="round"/><path d="M25 91H100Q126 91 126 62V48Q126 24 155 24" fill="none" stroke="#9dbd64" stroke-width="22" stroke-linecap="round"/><circle cx="158" cy="23" r="19" fill="#b0cb79" stroke="#31563f" stroke-width="2"/><circle cx="165" cy="16" r="5" fill="#fff"/><circle cx="167" cy="16" r="2.5" fill="#31563f"/><path d="M172 29q-5 4-9 0" fill="none" stroke="#31563f" stroke-width="2"/></svg><span>GOOD FOOD. GOOD MOOD.</span></div><p class="classic-kicker">THE ORIGINAL ONE-MORE-GO GAME</p><h2>A little hungry.<br>A lot of fun.</h2><p>Steer toward the apple. Every bite makes you longer. Stay inside the lawn, and keep your head away from your tail.</p><div class="speed-picker" role="group" aria-label="Game speed"><button data-speed="leisurely" aria-pressed="true">Leisurely</button><button data-speed="brisk" aria-pressed="false">Brisk</button><button data-speed="speedy" aria-pressed="false">Speedy</button></div><p class="classic-tip">Arrow keys / WASD to steer. Space pauses. On your phone, use the four direction buttons.</p><p class="picnic-note">No rush. Until you choose Speedy.</p><p class="classic-tip">Each speed keeps its own best. Choosing a speed sets up a fresh picnic.</p></aside></div>`;
  const canvas=$('#snake-canvas'),ctx=canvas.getContext('2d'),message=$('#snake-message'),start=$('#snake-start'),pauseButton=$('#snake-pause');
  function reset(){snake=[{x:7,y:9},{x:6,y:9},{x:5,y:9},{x:4,y:9}];direction=vectors.right;queued=null;food=snakeFood(snake,size);score=0;phase='ready';accumulator=0;last=0;$('#snake-score').textContent=0;best=record('snake-best-'+mode);$('#snake-best').textContent=best;start.textContent='Let’s picnic';pauseButton.disabled=true;draw();}
  function begin(){if(phase==='dead'||phase==='won')reset();phase='playing';start.textContent='Playing';start.disabled=true;pauseButton.disabled=false;last=performance.now();message.textContent='Follow your appetite. Watch your tail.';canvas.focus({preventScroll:true});}
  function pause(){if(phase!=='playing')return;phase='paused';queued=null;start.textContent='Keep picnicking';start.disabled=false;pauseButton.disabled=true;message.textContent='A little picnic break. Your apple can wait.';draw();}
  function steer(next){if(phase!=='playing')return;if((next.x===-direction.x&&next.y===-direction.y)||(next.x===direction.x&&next.y===direction.y))return;if(!queued)queued=next;}
  function end(won=false){phase=won?'won':'dead';start.textContent='One more picnic';start.disabled=false;pauseButton.disabled=true;message.textContent=won?'Every apple found. You have filled the whole lawn!':`Picnic over. ${score} ${score===1?'apple':'apples'} enjoyed. Ready for another?`;note(won?784:165,.25);draw();}
  function draw(){
    const tile=36;ctx.clearRect(0,0,648,648);ctx.fillStyle='#edf1d2';ctx.fillRect(0,0,648,648);
    for(let y=0;y<size;y++)for(let x=0;x<size;x++){ctx.fillStyle=(x+y)%2?'#e4ebc5':'#edf1d2';ctx.fillRect(x*tile,y*tile,tile,tile);ctx.fillStyle='#bac98b';ctx.fillRect(x*tile+8,y*tile+11,1.5,3);}
    ctx.strokeStyle='#54774b';ctx.lineWidth=3;ctx.strokeRect(1.5,1.5,645,645);
    if(food){const x=food.x*tile+18,y=food.y*tile+20;ctx.save();ctx.translate(x,y);ctx.fillStyle='#bbc98c';ctx.beginPath();ctx.ellipse(1,11,13,4,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e97655';ctx.strokeStyle='#9b4839';ctx.lineWidth=1.8;ctx.beginPath();ctx.moveTo(0,-9);ctx.bezierCurveTo(-20,-18,-19,8,-4,12);ctx.quadraticCurveTo(0,10,4,12);ctx.bezierCurveTo(19,8,20,-18,0,-9);ctx.fill();ctx.stroke();ctx.strokeStyle='#6c6640';ctx.beginPath();ctx.moveTo(0,-8);ctx.quadraticCurveTo(-2,-16,3,-18);ctx.stroke();ctx.fillStyle='#5a954e';ctx.beginPath();ctx.ellipse(8,-14,7,3,-.4,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ffcc97';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-9,-4);ctx.quadraticCurveTo(-13,0,-10,4);ctx.stroke();ctx.restore();}
    ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();snake.forEach((p,i)=>i?ctx.lineTo(p.x*tile+18,p.y*tile+18):ctx.moveTo(p.x*tile+18,p.y*tile+18));ctx.strokeStyle='#355f42';ctx.lineWidth=30;ctx.stroke();ctx.strokeStyle='#94b95d';ctx.lineWidth=25;ctx.stroke();
    snake.slice(1).forEach((p,i)=>{if(i%2===0){ctx.fillStyle='#bed488';ctx.beginPath();ctx.arc(p.x*tile+18,p.y*tile+18,4,0,Math.PI*2);ctx.fill();}});
    const head=snake[0];ctx.save();ctx.translate(head.x*tile+18,head.y*tile+18);ctx.rotate(Math.atan2(direction.y,direction.x));ctx.fillStyle=phase==='dead'?'#c3ba8d':'#b0cd79';ctx.strokeStyle='#355f42';ctx.lineWidth=1.8;ctx.beginPath();ctx.ellipse(2,0,17,14,0,0,Math.PI*2);ctx.fill();ctx.stroke();
    for(const y of [-9,9]){ctx.fillStyle='#fffbed';ctx.beginPath();ctx.arc(6,y,5.2,0,Math.PI*2);ctx.fill();ctx.fillStyle='#31563f';if(phase==='dead'){ctx.strokeStyle='#31563f';ctx.beginPath();ctx.moveTo(4,y-2);ctx.lineTo(8,y+2);ctx.moveTo(8,y-2);ctx.lineTo(4,y+2);ctx.stroke();}else{ctx.beginPath();ctx.arc(8,y,2.3,0,Math.PI*2);ctx.fill();}}
    ctx.strokeStyle='#d96954';ctx.lineWidth=1.8;ctx.beginPath();ctx.moveTo(18,0);ctx.lineTo(24,0);ctx.lineTo(28,-3);ctx.moveTo(24,0);ctx.lineTo(28,3);ctx.stroke();ctx.restore();
  }
  function tick(now){if(disposed)return;const dt=last?Math.min(now-last,250):0;last=now;if(phase==='playing'){accumulator+=dt;while(accumulator>=speeds[mode]&&phase==='playing'){accumulator-=speeds[mode];if(queued){direction=queued;queued=null;}const result=stepSnake(snake,direction,food,size);if(result.dead){end();break;}snake=result.body;if(result.ate){score++;$('#snake-score').textContent=score;if(score>best){best=score;save('snake-best-'+mode,best);$('#snake-best').textContent=best;}food=snakeFood(snake,size);note(420+score%6*65,.12);if(!food){end(true);break;}message.textContent=`${score} ${score===1?'apple':'apples'}. Plenty of appetite left.`;}draw();}}frame=requestAnimationFrame(tick);}
  start.addEventListener('click',begin);pauseButton.addEventListener('click',pause);
  canvas.addEventListener('keydown',event=>{const key=event.key.toLowerCase(),dir={arrowup:'up',w:'up',arrowdown:'down',s:'down',arrowleft:'left',a:'left',arrowright:'right',d:'right'}[key];if(dir){event.preventDefault();steer(vectors[dir]);}if(event.code==='Space'){event.preventDefault();if(event.repeat)return;phase==='playing'?pause():begin();}});
  $('#snake-directions').addEventListener('click',event=>{const button=event.target.closest('[data-dir]');if(button){steer(vectors[button.dataset.dir]);canvas.focus({preventScroll:true});}});
  document.querySelectorAll('[data-speed]').forEach(button=>button.addEventListener('click',()=>{mode=button.dataset.speed;document.querySelectorAll('[data-speed]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));start.disabled=false;reset();message.textContent=`${button.textContent} picnic. Ready when you are.`;}));
  function visibility(){if(document.hidden)pause();}window.addEventListener('blur',pause);document.addEventListener('visibilitychange',visibility);
  reset();frame=requestAnimationFrame(tick);return()=>{disposed=true;cancelAnimationFrame(frame);window.removeEventListener('blur',pause);document.removeEventListener('visibilitychange',visibility);};
}

function fieldNotes(){
  const difficulties={small:{cols:9,rows:9,count:10,label:'Pocket meadow'},large:{cols:12,rows:12,count:22,label:'Open meadow'}};
  let difficulty='small',cols=9,rows=9,count=10,field=null,revealed=[],flags=[],phase='ready',seconds=0,flagMode=false,focusIndex=0,timer=0,last=performance.now(),disposed=false;
  body.innerHTML=`<div class="classic-room field-room"><section class="classic-main"><div class="classic-toolbar"><div class="classic-stats">${stat('Mines left','mine-left','10')}${stat('Time','mine-time','0:00')}${stat('Best','mine-best','—')}</div><div class="field-seal" aria-hidden="true">LITTORA<br>FIELD CLUB</div></div><div class="field-board-wrap"><div class="mine-grid" id="mine-grid" role="group" aria-label="Minesweeper meadow"></div></div><div class="mine-controls"><div class="mine-mode" role="group" aria-label="Tap action"><button id="mine-reveal" aria-pressed="true">↗ Reveal</button><button id="mine-flag" aria-pressed="false">⚑ Flag</button></div><button id="new-game" class="subtle-button">New meadow</button></div><p class="classic-status" role="status" id="mine-message">Choose any patch. Your first step is always safe.</p>${restartPanel}</section><aside class="classic-sidebar"><div class="field-illustration" aria-hidden="true"><svg viewBox="0 0 230 150"><path d="M117 140Q87 80 119 9M105 119Q58 124 59 91Q85 82 105 119M99 88Q146 82 155 55Q117 45 99 88M101 59Q53 57 62 25Q96 29 101 59M111 32Q139 30 145 7Q117 7 111 32" fill="none" stroke="currentColor" stroke-width="1.7"/><path d="M157 134Q164 89 190 68M166 107q-20-23-5-35 14 8 5 35M179 82q23 2 25-17-18-4-25 17" fill="none" stroke="currentColor" stroke-width="1.2"/><path d="M40 134q5-28-6-39m5 22q-19-2-20-18 16 0 20 18m0-9q13-13 19-8-5 13-19 8" fill="none" stroke="currentColor"/><path d="M29 140H207" stroke="currentColor" stroke-width=".7"/></svg><span>SPECIMEN 006 · AN ORDINARY WONDER</span></div><p class="classic-kicker">A MINESWEEPER FIELD JOURNAL</p><h2>Read the meadow.</h2><p>Reveal every safe patch without uncovering a mine. A number tells you how many mines touch that patch, including diagonals.</p><div class="field-legend"><span class="legend-number">1</span><span>One neighbouring mine</span><span class="legend-flag">⚑</span><span>A place to tread carefully</span></div><p>Right-click or long-press to place a flag. On touch screens, switch to <strong>Flag</strong> and tap. Press <strong>F</strong> to flag a focused patch.</p><p class="classic-tip">Already flagged every mine around a number? Tap that number to reveal its remaining neighbours. Correct flags matter.</p><div class="difficulty-picker" role="group" aria-label="Meadow size"><button data-difficulty="small" aria-pressed="true"><strong>Pocket meadow</strong><span>9 × 9 · 10 mines</span></button><button data-difficulty="large" aria-pressed="false"><strong>Open meadow</strong><span>12 × 12 · 22 mines</span></button></div><p class="classic-tip">Changing size begins a new survey. Best times are kept separately. Use arrow keys to explore the grid.</p></aside></div>`;
  const grid=$('#mine-grid'),message=$('#mine-message');let cells=[];
  const clock=value=>`${Math.floor(value/60)}:${String(Math.floor(value)%60).padStart(2,'0')}`;
  function reset(){({cols,rows,count}=difficulties[difficulty]);field=null;revealed=Array(cols*rows).fill(false);flags=Array(cols*rows).fill(false);phase='ready';seconds=0;focusIndex=0;flagMode=false;$('#mine-flag').setAttribute('aria-pressed','false');$('#mine-reveal').setAttribute('aria-pressed','true');grid.classList.remove('flag-mode');last=performance.now();grid.style.setProperty('--cols',cols);grid.dataset.size=cols;grid.replaceChildren();cells=[];
    for(let i=0;i<cols*rows;i++){const cell=document.createElement('button');cell.type='button';cell.className='mine-cell';cell.tabIndex=i===0?0:-1;let held=0,origin=null,suppressUntil=0;
      cell.addEventListener('focus',()=>{focusIndex=i;cells.forEach((b,n)=>b.tabIndex=n===i?0:-1);});
      cell.addEventListener('click',()=>{if(performance.now()<suppressUntil)return;flagMode?flag(i):reveal(i);});
      cell.addEventListener('contextmenu',event=>{event.preventDefault();if(performance.now()<suppressUntil)return;flag(i);});
      cell.addEventListener('pointerdown',event=>{if(event.pointerType==='mouse'||event.button!==0)return;origin={x:event.clientX,y:event.clientY};held=setTimeout(()=>{flag(i);suppressUntil=performance.now()+800;held=0;},450);});
      const cancelHold=()=>{clearTimeout(held);held=0;origin=null;};
      cell.addEventListener('pointermove',event=>{if(origin&&Math.hypot(event.clientX-origin.x,event.clientY-origin.y)>10)cancelHold();});cell.addEventListener('pointerup',cancelHold);cell.addEventListener('pointercancel',cancelHold);cell.addEventListener('pointerleave',cancelHold);
      cell.addEventListener('keydown',event=>{if(event.key.toLowerCase()==='f'){event.preventDefault();flag(i);return;}const offset={ArrowLeft:-1,ArrowRight:1,ArrowUp:-cols,ArrowDown:cols}[event.key];if(offset!==undefined){event.preventDefault();const x=i%cols,y=Math.floor(i/cols);const next=event.key==='ArrowLeft'?y*cols+(x+cols-1)%cols:event.key==='ArrowRight'?y*cols+(x+1)%cols:event.key==='ArrowUp'?((y+rows-1)%rows)*cols+x:((y+1)%rows)*cols+x;cells[next].focus();}});
      cells.push(cell);grid.append(cell);
    }message.textContent='Choose any patch. Your first step is always safe.';render();}
  function render(){const terminal=phase==='lost'||phase==='won';cells.forEach((cell,i)=>{const open=revealed[i],mine=Boolean(field&&field[i]===-1),showMine=phase==='lost'&&mine,value=field?.[i]||0;cell.className='mine-cell'+(open?' revealed':'')+(flags[i]?' flagged':'')+(showMine?' exposed-mine':'')+(phase==='lost'&&flags[i]&&!mine?' wrong-flag':'');cell.dataset.number=open&&!mine?value:0;cell.disabled=terminal;cell.textContent=showMine?'✹':flags[i]?'⚑':open&&value>0?value:'';cell.setAttribute('aria-label',`Row ${Math.floor(i/cols)+1}, column ${i%cols+1}: ${showMine?'mine':flags[i]?'flagged':open?(value?value+' neighbouring '+(value===1?'mine':'mines'):'clear'):'unexplored'}`);});$('#mine-left').textContent=count-flags.filter(Boolean).length;$('#mine-time').textContent=clock(seconds);const best=record('mine-best-'+difficulty);$('#mine-best').textContent=best?clock(best):'—';grid.dataset.phase=phase;}
  function flag(index){if(phase==='lost'||phase==='won'||revealed[index])return;if(!flags[index]&&flags.filter(Boolean).length>=count){message.textContent='All flags are in use. Move one to a new patch.';return;}flags[index]=!flags[index];note(flags[index]?330:260,.08);render();message.textContent=flags[index]?'A careful note for later.':'Flag removed. A fresh look.';}
  function reveal(index){if(phase==='lost'||phase==='won')return;if(flags[index]){message.textContent='Remove the flag before exploring this patch.';return;}if(!field){field=createMinefield(cols,rows,count,index);phase='playing';last=performance.now();}const result=revealed[index]?chordMinefield(field,revealed,flags,index,cols,rows):revealMinefield(field,revealed,flags,index,cols,rows);revealed=result.revealed;
    if(result.hit){phase='lost';message.textContent='A hidden mine. New meadow, new discoveries. Take another walk.';note(150,.25);}
    else if(minefieldWon(field,revealed)){phase='won';flags=field.map(n=>n===-1);const completed=Math.max(1,Math.ceil(seconds)),best=record('mine-best-'+difficulty);seconds=completed;if(!best||completed<best)save('mine-best-'+difficulty,completed);message.textContent=`Meadow surveyed in ${clock(completed)}. Every safe patch discovered. Beautifully observed.`;note(660,.3);}
    else message.textContent='Follow the numbers. Every clue has a place.';render();}
  function setMode(flagging){flagMode=flagging;$('#mine-flag').setAttribute('aria-pressed',String(flagging));$('#mine-reveal').setAttribute('aria-pressed',String(!flagging));grid.classList.toggle('flag-mode',flagging);}
  $('#mine-flag').addEventListener('click',()=>setMode(true));$('#mine-reveal').addEventListener('click',()=>setMode(false));
  restartConfirmation(()=>{reset();cells[0].focus();});document.querySelectorAll('[data-difficulty]').forEach(button=>button.addEventListener('click',()=>{difficulty=button.dataset.difficulty;document.querySelectorAll('[data-difficulty]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));$('#restart-confirm').hidden=true;reset();cells[0].focus();}));
  function hidden(){last=performance.now();}document.addEventListener('visibilitychange',hidden);
  reset();timer=setInterval(()=>{if(disposed)return;const now=performance.now();if(phase==='playing'&&!document.hidden){seconds+=Math.min((now-last)/1000,1);$('#mine-time').textContent=clock(seconds);}last=now;},250);
  return()=>{disposed=true;clearInterval(timer);document.removeEventListener('visibilitychange',hidden);};
}
const dispose=game==='number'?numberloom():game==='snake'?picnicSnake():fieldNotes();
storageNotice();window.addEventListener('pagehide',()=>{dispose();audio?.close().catch(()=>{});},{once:true});window.addEventListener('pageshow',event=>{if(event.persisted)location.reload();});
